spring.application.name=anaf

server.port = 8085

# Enable hidden method filter untuk PATCH, PUT, DELETE
spring.mvc.hiddenmethod.filter.enabled=true

# Virtual thread
spring.threads.virtual.enabled=true

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=false
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.jpa.open-in-view=false

# Menambah waktu tunggu koneksi
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# log berwarna
spring.output.ansi.enabled=ALWAYS

## Config log aplikasi ##
logging.config=classpath:logback-spring.xml
